cognito.redirectUri=http://localhost:3000/apps/chess/login-callback
cognito.clientId=127nttui414onihc7vrt9dbf8i
cognito.endpoint=https://eu-north-1m7qbd8uy1.auth.eu-north-1.amazoncognito.com/oauth2/token

# Expose actuator endpoints
management.endpoints.web.exposure.include=health,info,prometheus,metrics
management.endpoints.web.base-path=/actuator

# Enable Prometheus registry
management.metrics.export.simple.enabled=false
management.metrics.export.prometheus.enabled=true
management.endpoint.prometheus.enabled=true