package com.crushedlemon.chess.dto.error;

public enum ErrorCode {
    ERROR_UNAUTHORIZED_NOT_IN_GAME,
    ERROR_UNAUTHORIZED_NOT_CURRENT_PLAYER,
    ERROR_UNAUTHORIZED_INCORRECT_PIECE_MOVED,
    ERROR_INVALID_MOVE,
    ERROR_INVALID_GAME,
    ERROR_RUNTIME_EXCEPTION
}
